site_name: $ sudo how
site_url: https://sudo.how/
theme:
  name: material
  custom_dir: overrides/
  palette: 

    # Palette toggle for light mode
    - scheme: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
